# Generated by Django 5.1.6 on 2025-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_choice',
            field=models.CharField(choices=[('classic', 'Classic'), ('professional', 'Professional'), ('modern', 'Modern'), ('elegant', 'Elegant')], default='classic', max_length=20),
        ),
    ]
