# Generated by Django 5.1.6 on 2025-06-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_template_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='achievements',
            field=models.TextField(default='No achievements yet'),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(default='No certifications yet'),
        ),
    ]
